image: "rust:slim"

stages:
  - check
  - build
  - test
  - release

variables:
  RUST_VERSION: stable

# Cache rust/cargo/build artifacts
cache:
  key: "$CI_PIPELINE_ID-$RUST_VERSION"
  paths:
    - /usr/local/cargo/registry/
    - /usr/local/rustup/toolchains/
    - /usr/local/rustup/update-hashes/
    - target/

# Install compiler and OpenSSL dependencies
before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends build-essential pkg-config libssl-dev
  - |
    rustup install $RUST_VERSION
    rustup default $RUST_VERSION
  - |
    rustc --version
    cargo --version

# Variable defaults
variables:
  RUST_VERSION: stable
  RUST_TARGET: x86_64-unknown-linux-gnu

# Check on stable, beta and nightly 
.check-base: &check-base
  stage: check
  script:
    - cargo check --verbose
    - cargo check --no-default-features --features send2 --verbose
    - cargo check --no-default-features --features send3 --verbose
    - cargo check --features no-color --verbose
rust-stable:
  <<: *check-base
rust-beta:
  <<: *check-base
  variables:
    RUST_VERSION: beta
rust-nightly:
  <<: *check-base
  variables:
    RUST_VERSION: nightly
rust-old:
  <<: *check-base
  variables:
    RUST_VERSION: "1.31"

# Build using Rust stable
build-x86_64-linux-gnu:
  stage: build
  script:
    - cargo build --target=$RUST_TARGET --release --verbose
    - mv target/$RUST_TARGET/release/ffsend ./ffsend
  artifacts:
    name: ffsend-x86_64-linux-gnu
    paths:
      - ffsend
    expire_in: 1 month

# Build a static version
build-x86_64-linux-musl:
  stage: build
  variables:
    RUST_TARGET: x86_64-unknown-linux-musl
  script:
    # Install the static target
    - rustup target add $RUST_TARGET

    # Build OpenSSL statically
    - apt install -y build-essential wget musl-tools
    - wget https://www.openssl.org/source/openssl-1.0.2o.tar.gz
    - tar xzvf openssl-1.0.2o.tar.gz
    - cd openssl-1.0.2o
    - ./config -fPIC --openssldir=/usr/local/ssl --prefix=/usr/local
    - make
    - make install
    - cd ..

    # Statically build ffsend
    - export OPENSSL_STATIC=1
    - export OPENSSL_LIB_DIR=/usr/local/lib
    - export OPENSSL_INCLUDE_DIR=/usr/local/include
    - cargo build --target=$RUST_TARGET --release --verbose

    # Prepare the release artifact
    - find . -name ffsend -exec ls -lah {} \;
    - mv target/$RUST_TARGET/release/ffsend ./ffsend
  artifacts:
    name: ffsend-x86_64-linux-musl
    paths:
      - ffsend
    expire_in: 1 month

# Run the unit tests through Cargo
cargo-test:
  stage: test
  dependencies: []
  script:
    - cargo test --verbose

# Run integration test with the public Send service
public-send-test:
  stage: test
  allow_failure: true
  dependencies:
    - build-x86_64-linux-musl
  variables:
    GIT_STRATEGY: none
  before_script: []
  script:
    # Generate random file, upload/download and assert equality
    - "head -c2m </dev/urandom >testfile"
    - "./ffsend upload testfile -d=10 -p=secret -I"
    - "./ffsend download $(./ffsend history -q) -p=secret -I -o=downloadfile"
    - "./ffsend delete $(./ffsend history -q)"
    - "cmp --silent ./testfile ./downloadfile || (echo ERROR: Downloaded file is different than original; exit 1)"

    # Also test Firefox Send v3
    - "./ffsend upload --host http://send2.dev.lcip.org/ testfile -d=10 -p=secret -I"
    - "./ffsend download $(./ffsend history -q) -p=secret -I -o=downloadfile2"
    - "./ffsend delete $(./ffsend history -q)"
    - "cmp --silent ./testfile ./downloadfile2 || (echo ERROR: Downloaded file is different than original; exit 1)"

# Cargo crate release
crate:
  stage: release
  only:
    - /^v(\d+\.)*\d+$/
  script:
    - echo "Creating release crate to publish on crates.io..."
    - echo $CARGO_TOKEN | cargo login
    - echo "Publishing crate to crates.io..."
    - cargo publish --verbose --allow-dirty

# AUR package release
pkg-aur:
  image: archlinux/base
  stage: release
  only:
    - /^v(\d+\.)*\d+$/
  before_script: []
  script:
    - cd ./pkg/aur

      # Update version number in PKGBUILD
    - VERSION=$(echo $CI_COMMIT_REF_NAME | cut -c 2-)
    - echo "Determined binary version number 'v$VERSION', updating PKGBUILD..."
    - sed "s/^pkgver=.*\$/pkgver=$VERSION/" -i PKGBUILD

      # Install dependencies
    - echo "Installing required build packages..."
    - pacman -Syu --noconfirm sudo base-devel binutils openssh rust cargo cmake git openssl

      # Make AUR package
    - echo "Making AUR package..."
    - mkdir -p /.cargo
    - chmod -R 777 /.cargo
    - sudo -u nobody makepkg -c
    - sudo -u nobody makepkg --printsrcinfo > .SRCINFO

      # Publish: set up SSH key, clone AUR repo, commit update and push
    - mkdir -p /root/.ssh
    - cp ./aur.pub /root/.ssh/id_rsa.pub
    - echo "$AUR_SSH_PRIVATE" > /root/.ssh/id_rsa
    - echo "Host aur.archlinux.org" >> /root/.ssh/config
    - echo "  IdentityFile /root/.ssh/aur" >> /root/.ssh/config
    - echo "  User aur" >> /root/.ssh/config
    - chmod 600 /root/.ssh/{id_rsa*,config}
    - eval `ssh-agent -s`
    - ssh-add /root/.ssh/id_rsa
    - ssh-keyscan -H aur.archlinux.org >> /root/.ssh/known_hosts
    - git config --global user.name "timvisee"
    - git config --global user.email "timvisee@gmail.com"
    - git clone ssh://aur@aur.archlinux.org/ffsend.git aur-ffsend
    - cd aur-ffsend
    - cp ../{PKGBUILD,.SRCINFO} ./
    - git add PKGBUILD .SRCINFO
    - git commit -m "Release v$VERSION"
    - git push

# # Snap release
# snap:
#   image: snapcore/snapcraft:edge
#   stage: release
#   # only:
#   #   - /^v(\d+\.)*\d+$/
#   before_script: []
#   script:
#     - echo "Building snap package..."
#     - cd pkg/snap
#     - snapcraft
#     # TODO: See: https://docs.snapcraft.io/rust-applications/7826
#     # TODO: - login to registry
#     # TODO: - test built snap
#     # TODO: - push snap to snapcraft.io
#     # - echo "Publishing snap package..."
#     # - echo "$SNAP_USER\n&SNAP_PASS" | snapcraft login
#     # - snapcraft push --release=edge ffsend_amd64.snap
