[package]
name = "ffsend-cli"
version = "0.1.0"
authors = ["timvisee <timvisee@gmail.com>"]
workspace = ".."

[[bin]]
path = "src/main.rs"
name = "ffsend"

[features]
default = ["clipboard"]

[dependencies]
clap = "2.31"
clipboard = { version = "0.4", optional = true }
ffsend-api = { version = "*", path = "../api" }
open = "1"
